---
- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --service-cidr={{ service_network_cidr }}
    --control-plane-endpoint=LOAD_BALANCER_DNS:6443
    --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig to root's home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Install network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
  when: network_plugin == "calico"

- name: Generate join command for workers
  command: kubeadm token create --print-join-command
  register: join_command
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Store join command
  set_fact:
    worker_join_command: "{{ join_command.stdout }}"
