---
- name: Install and configure Kubernetes cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Configure etcd cluster
  hosts: etcd
  become: yes
  roles:
    - etcd

- name: Configure Kubernetes master nodes
  hosts: masters
  become: yes
  roles:
    - master

- name: Configure Kubernetes worker nodes
  hosts: workers
  become: yes
  roles:
    - worker
