---
- name: Download etcd binary
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"

- name: Extract etcd archive
  unarchive:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create etcd data directory
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    mode: '0700'

- name: Generate etcd systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: Restart etcd

- name: Start and enable etcd service
  systemd:
    name: etcd
    state: started
    daemon_reload: yes
    enabled: yes
